---
# Audio system

- name: Install ALSA utilities
  community.general.pacman:
    name:
      - alsa-utils
      - alsa-plugins
    state: present

- name: Install PulseAudio
  community.general.pacman:
    name:
      - pulseaudio
    state: present
